version: '2'
services:
  web-postgres:
    container_name: web-postgres
    image: postgres:alpine
    env_file: .env
    environment:
      - POSTGRES_DB=test

  pg_backup_rsynced:
    container_name: pg_backup_rsynced
    image: coderat/docker-pg_backup_rsynced
    env_file: .env
    volumes:
      - ./data/backups:/mnt/backups            # backup destination
      - ./data/config:/mnt/config              # Directory with config files + crontab.txt
    expose:
      - '5432'
